"""Import every mapped model so metadata, Alembic, and tests see one schema."""

from app.db.models.assessment import (  # noqa: F401
    Assessment,
    AssessmentEvidence,
    AssessmentReview,
    ImmediateSafetyResult,
    IncidentUrgencyResult,
    ModelRun,
    SviResult,
)
from app.db.models.casework import (  # noqa: F401
    Case,
    CaseParticipant,
    CaseStatusEvent,
    Interaction,
    InteractionEvent,
    Subject,
    SubjectContact,
    TranscriptSegment,
    Translation,
)
from app.db.models.governance import (  # noqa: F401
    ConsentEvent,
    Jurisdiction,
    Organization,
    PolicyVersion,
    ProcessingAuthorityType,
    ProcessingAuthorization,
    ProcessingPurpose,
)
from app.db.models.platform import (  # noqa: F401
    AsyncJob,
    AuditEvent,
    DeletionRequest,
    IntegrationEvent,
)
from app.db.models.security import (  # noqa: F401
    AccessElevation,
    Actor,
    ActorIdentity,
    ActorRoleBinding,
    Role,
)
from app.db.models.support import (  # noqa: F401
    ContactAttempt,
    ContactAttemptPolicy,
    FollowUp,
    FollowUpPolicy,
    Referral,
    ReferralEvent,
    ResourceVerification,
    ServiceResource,
    SupportOutcome,
)

__all__ = [
    "Assessment",
    "AssessmentEvidence",
    "AssessmentReview",
    "ImmediateSafetyResult",
    "IncidentUrgencyResult",
    "ModelRun",
    "SviResult",
    "Case",
    "CaseParticipant",
    "CaseStatusEvent",
    "Interaction",
    "InteractionEvent",
    "Subject",
    "SubjectContact",
    "TranscriptSegment",
    "Translation",
    "ConsentEvent",
    "Jurisdiction",
    "Organization",
    "PolicyVersion",
    "ProcessingAuthorization",
    "ProcessingAuthorityType",
    "ProcessingPurpose",
    "AsyncJob",
    "AuditEvent",
    "DeletionRequest",
    "IntegrationEvent",
    "ContactAttempt",
    "ContactAttemptPolicy",
    "FollowUp",
    "FollowUpPolicy",
    "Referral",
    "ReferralEvent",
    "ResourceVerification",
    "ServiceResource",
    "SupportOutcome",
    "AccessElevation",
    "Actor",
    "ActorIdentity",
    "ActorRoleBinding",
    "Role",
]
